# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\gui.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1176, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 60))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frame_2.setStyleSheet("QPushButton {\n"
"background-color:#ffdf00; \n"
"border-radius:18px;\n"
"}\n"
"QPushButton:hover{background-color: #d4b617;}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_goto_home_sreen = QtWidgets.QPushButton(self.frame_2)
        self.btn_goto_home_sreen.setMinimumSize(QtCore.QSize(80, 80))
        self.btn_goto_home_sreen.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/assets/sharp_home_black_48dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_goto_home_sreen.setIcon(icon)
        self.btn_goto_home_sreen.setIconSize(QtCore.QSize(48, 48))
        self.btn_goto_home_sreen.setObjectName("btn_goto_home_sreen")
        self.verticalLayout_2.addWidget(self.btn_goto_home_sreen, 0, QtCore.Qt.AlignTop)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.btn_goto_config_screen = QtWidgets.QPushButton(self.frame_2)
        self.btn_goto_config_screen.setMinimumSize(QtCore.QSize(80, 80))
        self.btn_goto_config_screen.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/assets/baseline_settings_suggest_black_48dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_goto_config_screen.setIcon(icon1)
        self.btn_goto_config_screen.setIconSize(QtCore.QSize(48, 48))
        self.btn_goto_config_screen.setCheckable(False)
        self.btn_goto_config_screen.setObjectName("btn_goto_config_screen")
        self.verticalLayout_2.addWidget(self.btn_goto_config_screen, 0, QtCore.Qt.AlignBottom)
        self.horizontalLayout.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lbl_screen_title = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_screen_title.sizePolicy().hasHeightForWidth())
        self.lbl_screen_title.setSizePolicy(sizePolicy)
        self.lbl_screen_title.setMinimumSize(QtCore.QSize(656, 40))
        self.lbl_screen_title.setMaximumSize(QtCore.QSize(9999999, 40))
        font = QtGui.QFont()
        font.setFamily("Equinox Bold")
        font.setPointSize(12)
        self.lbl_screen_title.setFont(font)
        self.lbl_screen_title.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_screen_title.setObjectName("lbl_screen_title")
        self.verticalLayout_6.addWidget(self.lbl_screen_title)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_4)
        self.stackedWidget.setObjectName("stackedWidget")
        self.main_screen = QtWidgets.QWidget()
        self.main_screen.setObjectName("main_screen")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.main_screen)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_5 = QtWidgets.QFrame(self.main_screen)
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 250))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_17 = QtWidgets.QFrame(self.frame_5)
        self.frame_17.setMaximumSize(QtCore.QSize(500, 16777215))
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.graphicsView = QtWidgets.QGraphicsView(self.frame_17)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout_13.addWidget(self.graphicsView)
        self.horizontalLayout_7.addWidget(self.frame_17)
        self.frame_18 = QtWidgets.QFrame(self.frame_5)
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_18)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.frame_19 = QtWidgets.QFrame(self.frame_18)
        self.frame_19.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_19.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_19)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.rb_plc = QtWidgets.QRadioButton(self.frame_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_plc.sizePolicy().hasHeightForWidth())
        self.rb_plc.setSizePolicy(sizePolicy)
        self.rb_plc.setMinimumSize(QtCore.QSize(310, 0))
        self.rb_plc.setMaximumSize(QtCore.QSize(310, 16777215))
        font = QtGui.QFont()
        font.setFamily("Equinox Bold")
        font.setPointSize(12)
        self.rb_plc.setFont(font)
        self.rb_plc.setObjectName("rb_plc")
        self.horizontalLayout_8.addWidget(self.rb_plc)
        self.rb_test = QtWidgets.QRadioButton(self.frame_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_test.sizePolicy().hasHeightForWidth())
        self.rb_test.setSizePolicy(sizePolicy)
        self.rb_test.setMinimumSize(QtCore.QSize(310, 0))
        self.rb_test.setMaximumSize(QtCore.QSize(310, 16777215))
        font = QtGui.QFont()
        font.setFamily("Equinox Bold")
        font.setPointSize(12)
        self.rb_test.setFont(font)
        self.rb_test.setObjectName("rb_test")
        self.horizontalLayout_8.addWidget(self.rb_test)
        self.verticalLayout_17.addWidget(self.frame_19)
        self.frame_20 = QtWidgets.QFrame(self.frame_18)
        self.frame_20.setMinimumSize(QtCore.QSize(0, 48))
        self.frame_20.setMaximumSize(QtCore.QSize(16777215, 48))
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_20)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.le_file_for_test = QtWidgets.QLineEdit(self.frame_20)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_file_for_test.sizePolicy().hasHeightForWidth())
        self.le_file_for_test.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Equinox Bold")
        font.setPointSize(8)
        self.le_file_for_test.setFont(font)
        self.le_file_for_test.setObjectName("le_file_for_test")
        self.verticalLayout_14.addWidget(self.le_file_for_test)
        self.verticalLayout_17.addWidget(self.frame_20)
        self.frame_21 = QtWidgets.QFrame(self.frame_18)
        self.frame_21.setMinimumSize(QtCore.QSize(0, 48))
        self.frame_21.setMaximumSize(QtCore.QSize(16777215, 48))
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_21)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.frame_22 = QtWidgets.QFrame(self.frame_21)
        self.frame_22.setMaximumSize(QtCore.QSize(345, 16777215))
        self.frame_22.setStyleSheet("QPushButton{\n"
"background-color: #ffdf00;\n"
"color: #454545;\n"
"border-radius: 20px\n"
"}\n"
"QPushButton:hover{background-color: #d4b617;}\n"
"QPushButton:disabled{background-color: #cbcbcb}")
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_22)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.btn_search_file_for_test = QtWidgets.QPushButton(self.frame_22)
        self.btn_search_file_for_test.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_search_file_for_test.sizePolicy().hasHeightForWidth())
        self.btn_search_file_for_test.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Equinox Bold")
        font.setPointSize(12)
        self.btn_search_file_for_test.setFont(font)
        self.btn_search_file_for_test.setObjectName("btn_search_file_for_test")
        self.verticalLayout_15.addWidget(self.btn_search_file_for_test)
        self.horizontalLayout_9.addWidget(self.frame_22)
        self.frame_23 = QtWidgets.QFrame(self.frame_21)
        self.frame_23.setStyleSheet("QPushButton{\n"
"background-color: #ffdf00;\n"
"color: #454545;\n"
"border-radius: 20px\n"
"}\n"
"QPushButton:hover{background-color: #d4b617;}\n"
"QPushButton:disabled{background-color: #cbcbcb}")
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_23)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.btn_test_file = QtWidgets.QPushButton(self.frame_23)
        self.btn_test_file.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_test_file.sizePolicy().hasHeightForWidth())
        self.btn_test_file.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Equinox Bold")
        font.setPointSize(12)
        self.btn_test_file.setFont(font)
        self.btn_test_file.setObjectName("btn_test_file")
        self.verticalLayout_16.addWidget(self.btn_test_file)
        self.horizontalLayout_9.addWidget(self.frame_23)
        self.verticalLayout_17.addWidget(self.frame_21)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_17.addItem(spacerItem1)
        self.horizontalLayout_7.addWidget(self.frame_18)
        self.verticalLayout_4.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.main_screen)
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 260))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tbl_positions = QtWidgets.QTableWidget(self.frame_6)
        self.tbl_positions.setMinimumSize(QtCore.QSize(0, 250))
        self.tbl_positions.setObjectName("tbl_positions")
        self.tbl_positions.setColumnCount(0)
        self.tbl_positions.setRowCount(0)
        self.verticalLayout_5.addWidget(self.tbl_positions)
        self.verticalLayout_4.addWidget(self.frame_6)
        self.stackedWidget.addWidget(self.main_screen)
        self.config_screen = QtWidgets.QWidget()
        self.config_screen.setObjectName("config_screen")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.config_screen)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_7 = QtWidgets.QFrame(self.config_screen)
        self.frame_7.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_7.setStyleSheet("QPushButton{\n"
"background-color: #ffdf00;\n"
"color: #454545;\n"
"border-radius: 20px\n"
"}\n"
"QPushButton:hover{background-color: #d4b617;}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ico_cloud = QtWidgets.QLabel(self.frame_7)
        self.ico_cloud.setEnabled(True)
        self.ico_cloud.setMinimumSize(QtCore.QSize(50, 48))
        self.ico_cloud.setMaximumSize(QtCore.QSize(50, 16777215))
        self.ico_cloud.setText("")
        self.ico_cloud.setPixmap(QtGui.QPixmap(":/icons/assets/baseline_cloud_done_black_48dp.png"))
        self.ico_cloud.setObjectName("ico_cloud")
        self.horizontalLayout_2.addWidget(self.ico_cloud)
        self.rb_cloud_file = QtWidgets.QRadioButton(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_cloud_file.sizePolicy().hasHeightForWidth())
        self.rb_cloud_file.setSizePolicy(sizePolicy)
        self.rb_cloud_file.setMinimumSize(QtCore.QSize(310, 0))
        self.rb_cloud_file.setMaximumSize(QtCore.QSize(310, 16777215))
        font = QtGui.QFont()
        font.setFamily("Equinox Bold")
        font.setPointSize(12)
        self.rb_cloud_file.setFont(font)
        self.rb_cloud_file.setObjectName("rb_cloud_file")
        self.horizontalLayout_2.addWidget(self.rb_cloud_file)
        self.rb_local_file = QtWidgets.QRadioButton(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_local_file.sizePolicy().hasHeightForWidth())
        self.rb_local_file.setSizePolicy(sizePolicy)
        self.rb_local_file.setMinimumSize(QtCore.QSize(310, 0))
        self.rb_local_file.setMaximumSize(QtCore.QSize(310, 16777215))
        font = QtGui.QFont()
        font.setFamily("Equinox Bold")
        font.setPointSize(12)
        self.rb_local_file.setFont(font)
        self.rb_local_file.setObjectName("rb_local_file")
        self.horizontalLayout_2.addWidget(self.rb_local_file)
        self.verticalLayout_7.addWidget(self.frame_7, 0, QtCore.Qt.AlignTop)
        self.frame_8 = QtWidgets.QFrame(self.config_screen)
        self.frame_8.setMinimumSize(QtCore.QSize(0, 60))
        self.frame_8.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_8.setStyleSheet("QPushButton{\n"
"background-color: #ffdf00;\n"
"color: #454545;\n"
"border-radius: 20px\n"
"}\n"
"QPushButton:hover{background-color: #d4b617;}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_10 = QtWidgets.QFrame(self.frame_8)
        self.frame_10.setMinimumSize(QtCore.QSize(0, 48))
        self.frame_10.setMaximumSize(QtCore.QSize(16777215, 48))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.le_file_path = QtWidgets.QLineEdit(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_file_path.sizePolicy().hasHeightForWidth())
        self.le_file_path.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Equinox Bold")
        font.setPointSize(8)
        self.le_file_path.setFont(font)
        self.le_file_path.setObjectName("le_file_path")
        self.verticalLayout_10.addWidget(self.le_file_path)
        self.horizontalLayout_3.addWidget(self.frame_10)
        self.verticalLayout_7.addWidget(self.frame_8)
        self.frame_12 = QtWidgets.QFrame(self.config_screen)
        self.frame_12.setMinimumSize(QtCore.QSize(0, 48))
        self.frame_12.setMaximumSize(QtCore.QSize(16777215, 48))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_13 = QtWidgets.QFrame(self.frame_12)
        self.frame_13.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_13.sizePolicy().hasHeightForWidth())
        self.frame_13.setSizePolicy(sizePolicy)
        self.frame_13.setStyleSheet("QPushButton{\n"
"background-color: #ffdf00;\n"
"color: #454545;\n"
"border-radius: 20px\n"
"}\n"
"QPushButton:hover{background-color: #d4b617;}\n"
"QPushButton:disabled{background-color: #cbcbcb}")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.btn_search_file = QtWidgets.QPushButton(self.frame_13)
        self.btn_search_file.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_search_file.sizePolicy().hasHeightForWidth())
        self.btn_search_file.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Equinox Bold")
        font.setPointSize(12)
        self.btn_search_file.setFont(font)
        self.btn_search_file.setObjectName("btn_search_file")
        self.verticalLayout_11.addWidget(self.btn_search_file)
        self.horizontalLayout_4.addWidget(self.frame_13)
        self.verticalLayout_7.addWidget(self.frame_12)
        spacerItem2 = QtWidgets.QSpacerItem(30, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem2)
        self.stackedWidget.addWidget(self.config_screen)
        self.verticalLayout_3.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.frame_4)
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_screen_title.setText(_translate("MainWindow", "TextLabel"))
        self.rb_plc.setText(_translate("MainWindow", "CLP"))
        self.rb_test.setText(_translate("MainWindow", "Arquivo teste"))
        self.btn_search_file_for_test.setText(_translate("MainWindow", "Selecionar\n"
"Arquivo para teste"))
        self.btn_test_file.setText(_translate("MainWindow", "Testar arquivo"))
        self.rb_cloud_file.setText(_translate("MainWindow", "Habilita arquivo da nuvem"))
        self.rb_local_file.setText(_translate("MainWindow", "Habilita arquivo local"))
        self.btn_search_file.setText(_translate("MainWindow", "Selecionar\n"
"pasta"))

import ui_py.icon_rc
